# This file was generated by GoReleaser. DO NOT EDIT.
cask "lanxfer" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "3573a1f7e5d4122f73c4875c75ece400f53d8a1202f4709a4600dac5348f72c9"
      url "https://github.com/capybara-translation/lanxfer/releases/download/v#{version}/lanxfer_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f8f5d4e37cf00aba611f20a44e99cf558521190eb994c5c9e5c2d705ece392d"
      url "https://github.com/capybara-translation/lanxfer/releases/download/v#{version}/lanxfer_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d7e8ecc5e942cf13142d9637792704b1fadc018d71fb8eaf1ec79ea105760864"
      url "https://github.com/capybara-translation/lanxfer/releases/download/v#{version}/lanxfer_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0fea366a2e5f200903fc6dfbb3642452e3d171dff2b55912a4a15257dfbaa203"
      url "https://github.com/capybara-translation/lanxfer/releases/download/v#{version}/lanxfer_linux_amd64.tar.gz"
    end
  end

  name "lanxfer"
  desc "Send files directly between machines on your LAN"
  homepage "https://github.com/capybara-translation/lanxfer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lanxfer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lanxfer"]
    end
  end

  # No zap stanza required
end
