# This file was generated by GoReleaser. DO NOT EDIT.
cask "lanxfer" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "1645b7fce04eec704a36cccdb6cd261ad0cd7684e443c9e14c0ef57d88be79d3"
      url "https://github.com/capybara-translation/lanxfer/releases/download/v#{version}/lanxfer_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb7d21bf538bf9c9112d7fe446d29a7ad488e8d8aad19a7ae102860ca05de9bf"
      url "https://github.com/capybara-translation/lanxfer/releases/download/v#{version}/lanxfer_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7d413993d33c49c0c7e4f5c2db007ecf4c973c51670dac57865cd0c8e5d70df9"
      url "https://github.com/capybara-translation/lanxfer/releases/download/v#{version}/lanxfer_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f7d1ee718e1205f755020be89a5e39829098e4b5c27f1c58ec631fd778356800"
      url "https://github.com/capybara-translation/lanxfer/releases/download/v#{version}/lanxfer_linux_amd64.tar.gz"
    end
  end

  name "lanxfer"
  desc "Send files directly between machines on your LAN"
  homepage "https://github.com/capybara-translation/lanxfer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lanxfer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lanxfer"]
    end
  end

  # No zap stanza required
end
