# This file was generated by GoReleaser. DO NOT EDIT.
cask "zip2win" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "108507683d9072a5e3d8ef1f12db844117f569ce294921209a9e3d4d6c28c47c"
      url "https://github.com/capybara-translation/zip2win/releases/download/v#{version}/zip2win_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "93703e6bb94d69360b096126c425dc0014a0c547649e94dbb21a215a93d4a474"
      url "https://github.com/capybara-translation/zip2win/releases/download/v#{version}/zip2win_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "623a28eaac368f9977a828c128dcf500c47df4413ddd39957365338fe80b5fb7"
      url "https://github.com/capybara-translation/zip2win/releases/download/v#{version}/zip2win_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fec34f65ecd075ca90e603ed644578675d89ade5d86a58f69a9097ef97cabfd6"
      url "https://github.com/capybara-translation/zip2win/releases/download/v#{version}/zip2win_linux_amd64.tar.gz"
    end
  end

  name "zip2win"
  desc "Create ZIP archives that extract cleanly on Windows and check existing ones"
  homepage "https://github.com/capybara-translation/zip2win"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zip2win"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zip2win"]
    end
  end

  # No zap stanza required
end
