# This file was generated by GoReleaser. DO NOT EDIT.
cask "zip2win" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7259977b77b79c59de91e3b18a6f8e7190de67018ef636411a1a5eb8a3bcd5ea"
      url "https://github.com/capybara-translation/zip2win/releases/download/v#{version}/zip2win_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "972e786535fcd9eba7367f38442fe8aa9f2a9867eaa902a55552e9b092dc67ce"
      url "https://github.com/capybara-translation/zip2win/releases/download/v#{version}/zip2win_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b4362598bcb25f5b6435335555b055fa2161660228569e6db3984cc5f60e74df"
      url "https://github.com/capybara-translation/zip2win/releases/download/v#{version}/zip2win_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "17d6e717e62385fd2f597bc624b74c31b040c1d9b4b4f90dfb592c52c7453870"
      url "https://github.com/capybara-translation/zip2win/releases/download/v#{version}/zip2win_linux_amd64.tar.gz"
    end
  end

  name "zip2win"
  desc "Create ZIP archives that extract cleanly on Windows and check existing ones"
  homepage "https://github.com/capybara-translation/zip2win"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zip2win"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zip2win"]
    end
  end

  # No zap stanza required
end
