# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrec < Formula
  desc "Convert Claude Code conversation transcripts to Markdown"
  homepage "https://github.com/capybara-translation/ccrec"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.5.1/ccrec_darwin_amd64.tar.gz"
      sha256 "0eec88ed2c587ad99529a55266d11c83dbaf18f9c7dcb59137ec0425e7080de8"

      define_method(:install) do
        bin.install "ccrec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.5.1/ccrec_darwin_arm64.tar.gz"
      sha256 "d9721396d5ce4e88154bc315ef2d127d50d909fc0a26b81cc36874660aaa9854"

      define_method(:install) do
        bin.install "ccrec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.5.1/ccrec_linux_amd64.tar.gz"
      sha256 "e8eb480f0d5859a4b7350e4c432575f28c5224979dc2c7666a2f5b5e42ef502a"
      define_method(:install) do
        bin.install "ccrec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.5.1/ccrec_linux_arm64.tar.gz"
      sha256 "ce796b1ad7e4a23d7de59d801b922e3a12dcd09a5065901172e0e4029aff5318"
      define_method(:install) do
        bin.install "ccrec"
      end
    end
  end

  test do
    system "#{bin}/ccrec", "--version"
  end
end
