# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrec < Formula
  desc "Convert Claude Code conversation transcripts to Markdown"
  homepage "https://github.com/capybara-translation/ccrec"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.9.0/ccrec_darwin_amd64.tar.gz"
      sha256 "aedd1719cfa4105d7052500737572131cf3c308353d5cd0e195f7bf0bd0965b6"

      define_method(:install) do
        bin.install "ccrec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.9.0/ccrec_darwin_arm64.tar.gz"
      sha256 "ff0c82a8689398ef029b48aa01b7b929607c9213e0009cbf7ef1dfe9e7c2b3bc"

      define_method(:install) do
        bin.install "ccrec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.9.0/ccrec_linux_amd64.tar.gz"
      sha256 "ad7990866e601989e73ceddb84a788c0af9991ae258fb0cf69c57f09bfeb6796"
      define_method(:install) do
        bin.install "ccrec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.9.0/ccrec_linux_arm64.tar.gz"
      sha256 "d2dd93e74f86ea143117b29be128bf63738c9fe643e344b2d584494a82c10623"
      define_method(:install) do
        bin.install "ccrec"
      end
    end
  end

  test do
    system "#{bin}/ccrec", "--version"
  end
end
