# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccrec < Formula
  desc "Convert Claude Code conversation transcripts to Markdown"
  homepage "https://github.com/capybara-translation/ccrec"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.11.0/ccrec_darwin_amd64.tar.gz"
      sha256 "8130bf965a1c65d75ccbc58b454add22d094363626ec98339f8a8192c0a00832"

      define_method(:install) do
        bin.install "ccrec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.11.0/ccrec_darwin_arm64.tar.gz"
      sha256 "70af69e3be7cc14ea3bcaaaeb48f8a75c74ae5fbe95f46e578fbb7ae3250aca4"

      define_method(:install) do
        bin.install "ccrec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.11.0/ccrec_linux_amd64.tar.gz"
      sha256 "6b105b3c100004929b3f2bb215ad1c604e19517d98957953d4fa54a2e6c06a77"
      define_method(:install) do
        bin.install "ccrec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/capybara-translation/ccrec/releases/download/v0.11.0/ccrec_linux_arm64.tar.gz"
      sha256 "13925b6457ad7e943c2f0c1ec95dc73386fd5281a4a53c3d3fb76d4fffc8d160"
      define_method(:install) do
        bin.install "ccrec"
      end
    end
  end

  test do
    system "#{bin}/ccrec", "--version"
  end
end
