# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwlogs < Formula
  desc "Print AWS CloudWatch Logs events"
  homepage "https://github.com/capybara-translation/cwlogs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/capybara-translation/cwlogs/releases/download/v0.1.0/cwlogs_darwin_amd64.tar.gz"
      sha256 "63bd69f71251de0c6d213f25fe6fc903b168b06c22c2d623e21f10d5215a1b1c"

      define_method(:install) do
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/capybara-translation/cwlogs/releases/download/v0.1.0/cwlogs_darwin_arm64.tar.gz"
      sha256 "110084c7ec1d3b487c5d0579f1a0709ac8aefc9836f601ea4331b7b7aa2e1f4e"

      define_method(:install) do
        bin.install "cwlogs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/capybara-translation/cwlogs/releases/download/v0.1.0/cwlogs_linux_amd64.tar.gz"
      sha256 "2addfab7f39ec7d786facabdf52f47f48f1777b50bb9db92d420d155084a4ceb"
      define_method(:install) do
        bin.install "cwlogs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/capybara-translation/cwlogs/releases/download/v0.1.0/cwlogs_linux_arm64.tar.gz"
      sha256 "936be482c69beab92a4601d3a42b8cfdb171d6b544ae10b1582c32b95246cde5"
      define_method(:install) do
        bin.install "cwlogs"
      end
    end
  end

  test do
    system "#{bin}/cwlogs", "--version"
  end
end
